project:
  type: website
  output-dir: docs

website:
  title: "Mathematical Modeling"
  navbar:
    right:
      - href: "https://jeubank2-x.github.io/"
        icon: fa-home

format:
  html:
    theme:
      name: material
    css: styles.css
