name: Render Quarto/RMarkdown site

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.1' # latest R version

    - name: Install Quarto
      run: |
        sudo apt-get install wget -y
        wget https://github.com/quarto-dev/quarto-cli/releases/download/v2.16.3/quarto-2.16.3-linux-amd64.deb
        sudo dpkg -i quarto-2.16.3-linux-amd64.deb

    - name: Install R packages
      run: |
        Rscript -e 'install.packages(c("rmarkdown","knitr","kableExtra","deSolve","phaseR","pagedown","graphics","RColorBrewer","latex2exp","captioner"))'

    - name: Render site
      run: quarto render

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs  # your _site.yml output_dir
